name: ci-linux
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/ci-linux.yaml'
      - 'cabal.project'
      - '*/lib/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # install deps.
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev

      # cache libsodium
      - name: cache libsodium-1.0.18
        id: libsodium
        uses: actions/cache@v2
        with:
          path: ~/libsodium-stable
          key: ${{ runner.os }}-libsodium-1.0.18

      # install libsodium with cache
      - name: Install cache libsodium-1.0.18
        if: steps.libsodium.outputs.cache-hit == 'true'
        run: cd ~/libsodium-stable && ./configure && make -j2 && sudo make install

      # download & install libsodium without cache
      - name: Install libsodium
        if: steps.libsodium.outputs.cache-hit != 'true'
        run: |
          wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable.tar.gz
          tar -xvzf libsodium-1.0.18-stable.tar.gz -C ~
          cd ~/libsodium-stable
          ./configure
          make -j2 && make check
          sudo make install
          cd -

      - name: Cache .cabal
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal
          key: cabal

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10' # Resolves to the latest point release of GHC 8.10
          cabal-version: '3.6.0.0' # Exact version of Cabal

      - uses: actions/checkout@v2

      - name: build convex-muesli-core convex-muesli-data-export convex-node-client convex-options convex-prices
        run: cabal build -j build convex-muesli-core convex-muesli-data-export convex-node-client convex-options convex-prices

      - name: run convex-options-test
        run: cabal run convex-options-test
